/** Códigos estables de fallos esperados por la capa de presentación. */
export type ApplicationErrorCode =
  | 'EMAIL_ALREADY_REGISTERED'
  | 'EMAIL_VERIFICATION_UNAVAILABLE'
  | 'EMAIL_VERIFICATION_INVALID'
  | 'EMAIL_NOT_VERIFIED'
  | 'INVALID_CREDENTIALS'
  | 'EXTERNAL_AUTH_UNAVAILABLE'
  | 'EXTERNAL_IDENTITY_INVALID'
  | 'EXTERNAL_ACCOUNT_LINK_REQUIRED'
  | 'EXTERNAL_PROFILE_EXPIRED'
  | 'EXTERNAL_IDENTITY_CONFLICT'
  | 'CURRENT_PASSWORD_INVALID'
  | 'PASSWORD_CHANGE_UNAVAILABLE'
  | 'RECOVERY_UNAVAILABLE'
  | 'RESET_LINK_INVALID'
  | 'PROFILE_UPDATE_CONFLICT'
  | 'USER_NOT_FOUND'
  | 'ROUTINE_EXERCISE_NOT_FOUND'
  | 'ROUTINE_PLAN_NOT_FOUND'
  | 'ROUTINE_HISTORY_NOT_FOUND'
  | 'ROUTINE_CURRENT_DELETE_FORBIDDEN'
  | 'TRAINING_RELATION_REQUIRED'
  | 'CALORIE_CALCULATION_NOT_FOUND'
  | 'CALORIE_PROFILE_REQUIRED'
  | 'DIET_PLAN_NOT_FOUND'
  | 'NUTRITION_RELATION_REQUIRED'
  | 'SESSION_UNAVAILABLE'
  | 'SPECIALIST_PROFILE_ALREADY_EXISTS'
  | 'SPECIALIST_PROFILE_NOT_FOUND'
  | 'SPECIALIST_ROLE_UNAVAILABLE'
  | 'SPECIALIST_SELF_REQUEST'
  | 'SPECIALIST_REQUEST_CONFLICT'
  | 'SPECIALIST_REQUEST_NOT_FOUND';

/** Error de caso de uso que puede traducirse a una respuesta segura. */
export class ApplicationError extends Error {
  constructor(
    /** Código estable; no contiene información sensible. */
    readonly code: ApplicationErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'ApplicationError';
  }
}
